"""Transmon layer for the 1qb-DB experiment.

The demo notebook (``1qb-DB-demo.ipynb``) works entirely in the normalized
two-level picture, where a waveform is a dimensionless pair
``(t/Tg, Tg*Omega)``.  A transmon adds two things that picture cannot see:

* **leakage** to the second excited state, set by the peak drive measured
  against the anharmonicity ``alpha``;
* **decoherence**, set by the gate duration measured against ``T1``/``T2``.

Those two costs pull in opposite directions along the one gauge freedom the
normalized waveform still has.  Rescaling a curve leaves every dimensionless
quantity ``Tg*Omega_max``, ``int Omega dt``, tantrix area, ... unchanged while
trading ``Tg`` against ``Omega`` (see the repository README section 4).  This
module fixes that gauge the way a laboratory does: **every pulse is driven at
the same peak Rabi rate** ``DEVICE.rabi_max``, so each waveform gets the gate
time its own shape demands.  Leakage is then held roughly level across the
comparison and the price of robustness shows up as gate time.

Everything here is single-qubit and perturbative in the leakage coupling; the
full three-level propagation lives in the later sections of the notebook, and
:func:`leakage_amplitude` is deliberately written so that it can be checked
against it.

The normalized-waveform loading, ideal propagators and error-curve geometry are
reused from :mod:`db_helpers` rather than reimplemented.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

import db_helpers


HERE = Path(__file__).resolve().parent
TRANSMON_DIR = HERE / "transmon_waveforms"

TWO_PI = 2.0 * np.pi


# --- device ------------------------------------------------------------------


@dataclass(frozen=True)
class TransmonDevice:
    """Fixed hardware parameters, in laboratory units.

    Frequencies are ordinary frequencies in GHz (so ``0.05`` is 50 MHz) and
    times are in ns.  Angular rates used by the Hamiltonian are obtained from
    the ``*_rate`` properties, which multiply by ``2*pi``.

    Attributes
    ----------
    anharmonicity : float
        ``alpha/2pi`` in GHz, negative for a transmon.  Sets the 1-2 detuning
        in the frame rotating with a drive resonant on 0-1.
    rabi_max : float
        ``Omega_max/2pi`` in GHz, the peak drive every pulse is normalized to.
    t1, t2_echo : float
        Relaxation and echo coherence times in ns.
    sample_rate : float
        AWG sample rate in GS/s, i.e. samples per ns.
    """

    anharmonicity: float = -0.200
    rabi_max: float = 0.050
    t1: float = 60_000.0
    t2_echo: float = 60_000.0
    sample_rate: float = 2.4

    @property
    def anharmonicity_rate(self) -> float:
        """``alpha`` in rad/ns (negative)."""
        return TWO_PI * self.anharmonicity

    @property
    def rabi_max_rate(self) -> float:
        """``Omega_max`` in rad/ns."""
        return TWO_PI * self.rabi_max


DEVICE = TransmonDevice()


# --- normalized waveforms -----------------------------------------------------

#: Waveforms exported by ``X_gate_pulse_generation``.  ``barq_amplitude_robust``
#: is deliberately absent: it carries a constant detuning and the experiment is
#: resonant-only.
IMPORTED_WAVEFORMS = {
    "Gaussian": "gaussian_x_pi.csv",
    "Resonant composite": "resonant_composite_robust_x_pi.csv",
    "BARQ resonant (smooth)": "barq_resonant_screening_x_pi.csv",
}


def load_imported_waveforms(names=None):
    """Load the resonant waveforms exported by the generator.

    Parameters
    ----------
    names : iterable of str, optional
        Subset of :data:`IMPORTED_WAVEFORMS` keys.  Defaults to all of them.

    Returns
    -------
    dict
        ``{display name: structured array}`` in the normalized CSV convention
        ``time_over_Tg, Tg_omega_x, Tg_omega_y, Tg_omega_envelope, phase_rad,
        Tg_delta``.
    """
    selected = IMPORTED_WAVEFORMS if names is None else {
        name: IMPORTED_WAVEFORMS[name] for name in names
    }
    return {
        name: db_helpers.load_waveform(filename)
        for name, filename in selected.items()
    }


def load_transmon_waveform(stem):
    """Load a waveform generated by this module from ``transmon_waveforms/``."""
    return np.genfromtxt(
        TRANSMON_DIR / f"{stem}.csv",
        delimiter=",",
        names=True,
    )


# --- gauge fixing: normalized -> physical -------------------------------------


def to_physical(pulse, device=DEVICE):
    """Place a normalized waveform on the device at fixed peak Rabi rate.

    The gate time follows from the shape,

    .. math:: T_g = \\max_s |T_g\\Omega(s)| / \\Omega_{\\max},

    so a waveform whose normalized peak is large (a robust pulse) becomes a
    long gate rather than an over-driven one.  This is the single gauge choice
    that the whole transmon comparison rests on.

    Returns
    -------
    dict
        ``time`` (ns), ``omega_x``/``omega_y``/``omega``/``delta`` (rad/ns),
        ``phase`` (rad), ``gate_time`` (ns) and ``peak_tg_omega``
        (dimensionless, the invariant that set the gate time).
    """
    peak = float(np.max(np.abs(pulse["Tg_omega_envelope"])))
    gate_time = peak / device.rabi_max_rate
    return {
        "time": pulse["time_over_Tg"] * gate_time,
        "omega_x": pulse["Tg_omega_x"] / gate_time,
        "omega_y": pulse["Tg_omega_y"] / gate_time,
        "omega": pulse["Tg_omega_envelope"] / gate_time,
        "phase": pulse["phase_rad"],
        "delta": pulse["Tg_delta"] / gate_time,
        "gate_time": gate_time,
        "peak_tg_omega": peak,
    }


# --- first-order leakage ------------------------------------------------------


def leakage_amplitude(pulse, device=DEVICE):
    """First-order leakage amplitude ``c_2`` out of ``|0>`` at the gate end.

    Split the three-level rotating-frame Hamiltonian into the driven qubit
    block, which is treated exactly, and the coupling to ``|2>``, which is
    treated to first order.  With the drive resonant on 0-1 the second level
    sits at ``alpha`` and the ladder matrix element carries the usual
    ``sqrt(2)``, so

    .. math::
        c_2 = -\\tfrac{i}{\\sqrt2}\\int_0^{T_g}\\!\\Omega(t)\\,
              e^{i\\Phi(t)}e^{i\\alpha t}\\,\\langle 1|U_{01}(t)|0\\rangle\\,dt .

    Written in normalized time the integrand depends on the waveform only
    through the exported dimensionless fields and the single number
    ``alpha*Tg`` -- which is exactly where the gate-time/leakage trade-off
    enters.  No DRAG correction is applied: the ``|2>`` amplitude reported here
    is what the bare waveform produces.

    Returns
    -------
    dict
        ``amplitude`` (complex ``c_2``), ``population`` (``|c_2|^2``),
        ``alpha_Tg`` and ``drive_ratio`` = ``Omega_max/|alpha|``.
    """
    physical = to_physical(pulse, device)
    alpha_tg = device.anharmonicity_rate * physical["gate_time"]

    time = pulse["time_over_Tg"]
    drive = pulse["Tg_omega_x"] + 1j * pulse["Tg_omega_y"]
    # <1|U_01(t)|0>, the qubit amplitude the leakage coupling acts on.
    u10 = db_helpers.ideal_propagators(pulse)[:, 1, 0]

    integrand = drive * np.exp(1j * alpha_tg * time) * u10
    amplitude = -1j / np.sqrt(2.0) * np.trapezoid(integrand, time)
    return {
        "amplitude": complex(amplitude),
        "population": float(abs(amplitude) ** 2),
        "alpha_Tg": float(alpha_tg),
        "drive_ratio": device.rabi_max_rate / abs(device.anharmonicity_rate),
    }


def three_level_propagation(pulse, device=DEVICE, coupling=1.0, stride=1):
    """Propagate ``|0>`` through the exact three-level RWA Hamiltonian.

    In the frame rotating with a drive resonant on 0-1, and after the RWA,

    .. math::
        H = \\alpha|2\\rangle\\langle2| + \\tfrac12\\big[
            (\\Omega_x - i\\Omega_y)\\,a + \\mathrm{h.c.}\\big],\\qquad
        a = |0\\rangle\\langle1| + \\sqrt2\\,|1\\rangle\\langle2| ,

    integrated as an ordered product of midpoint exponentials, exactly as the
    two-level demo does.  No DRAG correction and no decoherence: this is the
    leakage the bare waveform produces.

    Parameters
    ----------
    coupling : float
        Scales the 1-2 ladder element only.  ``coupling -> 0`` recovers the
        perturbative limit and is how :func:`leakage_amplitude` is verified.
    stride : int
        Subsample the waveform before propagating.  The exported grids carry
        2501 points; ``stride=4`` changes the results in the fourth digit.

    Returns
    -------
    dict
        ``populations`` (3,) at the gate end and ``leakage`` = ``P2``.
    """
    from scipy.linalg import expm

    physical = to_physical(pulse, device)
    time = physical["time"][::stride]
    omega_x = physical["omega_x"][::stride]
    omega_y = physical["omega_y"][::stride]

    lower = np.diag([1.0, coupling * np.sqrt(2.0)], 1)
    bare = np.diag([0.0, 0.0, device.anharmonicity_rate]).astype(complex)

    state = np.array([1.0, 0.0, 0.0], dtype=complex)
    mid_x = 0.5 * (omega_x[:-1] + omega_x[1:])
    mid_y = 0.5 * (omega_y[:-1] + omega_y[1:])
    for step, (x_value, y_value) in zip(np.diff(time), zip(mid_x, mid_y)):
        drive = 0.5 * (
            (x_value - 1j * y_value) * lower
            + (x_value + 1j * y_value) * lower.conj().T
        )
        state = expm(-1j * (bare + drive) * step) @ state
    populations = np.abs(state) ** 2
    return {
        "populations": populations,
        "leakage": float(populations[2]),
    }


def drive_spectrum(pulse, device=DEVICE, span=0.6, points=1201):
    """Complex-envelope spectrum of the drive, in laboratory frequency units.

    Returns the magnitude of ``int Omega(t) e^{i Phi(t)} e^{i 2 pi f t} dt``
    over ``f`` in ``[-span, span]`` GHz.  This is the textbook leakage picture:
    weight at ``f = alpha/2pi`` drives the 1-2 transition.  It omits the
    ``<1|U_01|0>`` factor kept by :func:`leakage_amplitude`, so it is a reading
    aid, not the quantitative estimate.

    Returns
    -------
    dict
        ``frequency`` (GHz) and ``weight`` (rad, i.e. an angle).
    """
    physical = to_physical(pulse, device)
    time = physical["time"]
    drive = physical["omega_x"] + 1j * physical["omega_y"]
    frequency = np.linspace(-span, span, points)
    kernel = np.exp(1j * TWO_PI * np.outer(frequency, time))
    weight = np.abs(np.trapezoid(kernel * drive, time, axis=1))
    return {"frequency": frequency, "weight": weight}


# --- per-pulse summary --------------------------------------------------------


def pulse_metrics(pulse, device=DEVICE, leakage_stride=4):
    """Dimensionless geometry plus the physical cost of running the pulse.

    The dimensionless block is gauge invariant and reproduces the demo
    notebook; the physical block is what the choice of :func:`to_physical`
    turns that geometry into on this device.  Both the perturbative and the
    exact three-level leakage are reported, because at ``Omega_max/|alpha| =
    0.25`` first order is only a screen (see the notebook).
    """
    physical = to_physical(pulse, device)
    # Both noise channels, both orders.  "amplitude" is the multiplicative
    # control error this experiment injects, (Omega_x, Omega_y) ->
    # (1+eps)(Omega_x, Omega_y); "dephasing" is the static detuning channel.
    # Closure carries the first order, the signed area the second.
    curve = db_helpers.error_curve(pulse, noise="amplitude")
    dephasing = db_helpers.error_curve(pulse, noise="dephasing")
    leakage = leakage_amplitude(pulse, device)
    exact = three_level_propagation(pulse, device, stride=leakage_stride)
    gate = db_helpers.time_ordered_gate(pulse, 0.0)

    time = pulse["time_over_Tg"]
    envelope = np.abs(pulse["Tg_omega_envelope"])
    gate_time = physical["gate_time"]

    return {
        # gauge-invariant geometry
        "peak_Tg_omega": physical["peak_tg_omega"],
        "pulse_area": float(np.trapezoid(envelope, time)),
        "energy": float(np.trapezoid(envelope**2, time)),
        "closure": curve["closure"],
        "area_norm": float(np.linalg.norm(curve["area"])),
        "dephasing_closure": dephasing["closure"],
        "dephasing_area_norm": float(np.linalg.norm(dephasing["area"])),
        "zero_error_infidelity": 1.0 - db_helpers.average_gate_fidelity(gate),
        # physical, at fixed peak Rabi rate
        "gate_time_ns": gate_time,
        "drive_over_alpha": leakage["drive_ratio"],
        "leakage_P2_first_order": leakage["population"],
        "leakage_P2": exact["leakage"],
        "Tg_over_T1": gate_time / device.t1,
        "Tg_over_T2": gate_time / device.t2_echo,
    }


#: ``(group title, [(metric key, column title, format)])``.  The grouping is the
#: point of the table: robustness has two independent noise channels and two
#: orders in each, and a pulse can be excellent in one cell and useless in the
#: neighbouring one.
METRIC_GROUPS = (
    ("drive cost", (
        ("peak_Tg_omega", "Tg*Om_max", "{:11.3f}"),
        ("pulse_area", "area/pi", "{:9.3f}"),
    )),
    ("control error", (
        ("closure", "1st |R(T)-R(0)|", "{:17.3e}"),
        ("area_norm", "2nd |A|", "{:12.3e}"),
    )),
    ("dephasing error", (
        ("dephasing_closure", "1st |R(T)-R(0)|", "{:17.3e}"),
        ("dephasing_area_norm", "2nd |A|", "{:12.3e}"),
    )),
    ("on this device", (
        ("zero_error_infidelity", "1-F(eps=0)", "{:12.2e}"),
        ("gate_time_ns", "Tg [ns]", "{:10.2f}"),
        ("leakage_P2", "P2 (exact)", "{:13.3e}"),
    )),
)

METRIC_COLUMNS = tuple(
    column for _, columns in METRIC_GROUPS for column in columns
)


def print_metrics_table(pulses, device=DEVICE):
    """Print the section-1 summary table and return the raw metric dict.

    Columns are grouped: what the drive costs, how the pulse survives a
    multiplicative *control* error, how it survives *dephasing*, and what the
    device charges for it.  Closure is the first-order measure of each channel
    and the signed area the second-order one; a pulse that closes its curve but
    encloses a large area is robust only to leading order.
    """
    metrics = {
        name: pulse_metrics(pulse, device)
        for name, pulse in pulses.items()
    }
    label_width = max(len(name) for name in metrics) + 2

    print(
        f"peak drive fixed at Omega_max/2pi = {device.rabi_max * 1e3:.0f} MHz,"
        f"  alpha/2pi = {device.anharmonicity * 1e3:.0f} MHz,"
        f"  T1 = T2echo = {device.t1 / 1e3:.0f} us"
    )
    print(
        "control error = (Om_x,Om_y) -> (1+eps)(Om_x,Om_y);"
        "  dephasing error = static delta_z."
        "  Closure is 1st order, signed area 2nd."
    )

    widths = [
        sum(len(fmt.format(0.0)) for _, _, fmt in columns)
        for _, columns in METRIC_GROUPS
    ]
    group_row = f"{'':{label_width}s}" + "".join(
        f"{title[:width - 2]:^{width}s}"
        for (title, _), width in zip(METRIC_GROUPS, widths)
    )
    header = f"{'pulse':{label_width}s}" + "".join(
        f"{title:>{len(fmt.format(0.0))}s}"
        for _, title, fmt in METRIC_COLUMNS
    )
    print(group_row)
    print(header)
    print("-" * len(header))
    for name, values in metrics.items():
        row = f"{name:{label_width}s}"
        for key, _, fmt in METRIC_COLUMNS:
            value = values[key]
            if key == "pulse_area":
                value = value / np.pi
            row += fmt.format(value)
        print(row)
    return metrics


# --- plots --------------------------------------------------------------------


#: Anharmonicities to sweep when reporting leakage, in GHz.  A single value is
#: not safe to quote: the drive spectrum has deep, narrow nulls, and whether
#: ``alpha`` happens to land in one is an accident of the numbers.
ANHARMONICITY_SWEEP = (-0.170, -0.185, -0.200, -0.215, -0.230, -0.250)


def leakage_vs_anharmonicity(pulses, device=DEVICE,
                             anharmonicities=ANHARMONICITY_SWEEP, stride=4):
    """Exact three-level leakage across a band of anharmonicities.

    The peak Rabi rate stays fixed, so each pulse keeps its gate time and only
    the 1-2 detuning moves.  Reporting the band rather than one number is the
    honest form: individual values swing by two orders of magnitude as
    ``alpha`` slides across a spectral null, while the *ordering* between
    waveforms does not.

    Returns
    -------
    dict
        ``{name: {"values": array, "min": float, "max": float}}``.
    """
    results = {}
    for name, pulse in pulses.items():
        values = np.array([
            three_level_propagation(
                pulse,
                TransmonDevice(
                    anharmonicity=alpha,
                    rabi_max=device.rabi_max,
                    t1=device.t1,
                    t2_echo=device.t2_echo,
                    sample_rate=device.sample_rate,
                ),
                stride=stride,
            )["leakage"]
            for alpha in anharmonicities
        ])
        results[name] = {
            "values": values,
            "min": float(values.min()),
            "max": float(values.max()),
        }
    return results


def print_leakage_band(pulses, device=DEVICE,
                       anharmonicities=ANHARMONICITY_SWEEP):
    """Print :func:`leakage_vs_anharmonicity` as a table."""
    results = leakage_vs_anharmonicity(pulses, device, anharmonicities)
    header = f"{'pulse':26s}" + "".join(
        f"{alpha * 1e3:>13.0f}" for alpha in anharmonicities
    )
    print("exact three-level P2, alpha/2pi [MHz] across the top")
    print(header)
    print("-" * len(header))
    for name, result in results.items():
        print(f"{name:26s}" + "".join(f"{v:13.3e}" for v in result["values"]))
    print()
    print(f"{'pulse':26s}{'worst case P2':>15s}")
    for name, result in results.items():
        print(f"{name:26s}{result['max']:15.3e}")
    return results


def verify_leakage_formula(pulses, device=DEVICE, couplings=(1.0, 0.3, 0.1, 0.03),
                           stride=4):
    """Check :func:`leakage_amplitude` against the exact propagation.

    Scaling the 1-2 ladder element by ``lambda`` makes the exact leakage
    ``lambda^2 |c_2|^2 + O(lambda^4)``, so ``P2(lambda)/lambda^2`` must
    approach the perturbative value.  This isolates "is the formula right"
    from "is first order accurate here", which are different questions at
    ``Omega_max/|alpha| = 0.25``.
    """
    print(
        f"{'pulse':26s}{'|c2|^2':>15s}"
        + "".join(f"{f'P2/l^2, l={c:g}':>16s}" for c in couplings)
    )
    for name, pulse in pulses.items():
        row = f"{name:26s}{leakage_amplitude(pulse, device)['population']:15.6e}"
        for coupling in couplings:
            exact = three_level_propagation(
                pulse, device, coupling=coupling, stride=stride
            )
            row += f"{exact['leakage'] / coupling**2:16.6e}"
        print(row)


def plot_physical_controls(pulses, device=DEVICE, colors=None):
    """Overlay the quadratures of every pulse on one laboratory time axis.

    Everything is drawn in MHz (``Omega/2pi``) against ns, with the shared peak
    drive marked, so the comparison reads directly as "same amplitude,
    different duration".
    """
    import matplotlib.pyplot as plt

    colors = colors or color_cycle(pulses)
    figure, axes = plt.subplots(2, 1, figsize=(9.5, 6), sharex=True)
    for name, pulse in pulses.items():
        physical = to_physical(pulse, device)
        time = physical["time"]
        color = colors[name]
        axes[0].plot(
            time,
            physical["omega_x"] / TWO_PI * 1e3,
            color=color,
            label=f"{name}, $T_g$={physical['gate_time']:.1f} ns",
        )
        axes[1].plot(
            time,
            physical["omega_y"] / TWO_PI * 1e3,
            color=color,
            label=name,
        )
    for axis, quadrature in zip(axes, ("x", "y")):
        axis.axhline(0.0, color="0.6", linewidth=0.8)
        axis.set_ylabel(rf"$\Omega_{quadrature}/2\pi$ [MHz]")
        axis.grid(alpha=0.25)
    for sign in (+1, -1):
        axes[0].axhline(
            sign * device.rabi_max * 1e3,
            color="0.3",
            linestyle=":",
            linewidth=1.0,
        )
    axes[0].set_title(
        "control waveforms at fixed peak drive "
        rf"($\Omega_\mathrm{{max}}/2\pi$ = {device.rabi_max * 1e3:.0f} MHz,"
        " dotted)"
    )
    axes[0].legend(fontsize=8, loc="upper right")
    axes[-1].set_xlabel("time [ns]")
    figure.tight_layout()
    return figure


def plot_drive_spectra(pulses, device=DEVICE, colors=None, span=0.6):
    """Show where each drive puts spectral weight relative to ``alpha``."""
    import matplotlib.pyplot as plt

    colors = colors or color_cycle(pulses)
    figure, axis = plt.subplots(figsize=(9.5, 4.6))
    peak = 0.0
    for name, pulse in pulses.items():
        spectrum = drive_spectrum(pulse, device, span=span)
        exact = three_level_propagation(pulse, device, stride=4)
        peak = max(peak, spectrum["weight"].max())
        axis.semilogy(
            spectrum["frequency"] * 1e3,
            spectrum["weight"],
            color=colors[name],
            linewidth=1.2,
            label=f"{name}, $P_2$={exact['leakage']:.1e}",
        )
        # The one value the reader is here for: the weight sitting on the 1-2
        # transition.  The nulls elsewhere are sinc structure, not physics.
        at_alpha = np.interp(
            device.anharmonicity, spectrum["frequency"], spectrum["weight"]
        )
        axis.plot(
            device.anharmonicity * 1e3,
            at_alpha,
            marker="o",
            markersize=7,
            color=colors[name],
            markeredgecolor="white",
            zorder=5,
        )
    axis.axvline(
        device.anharmonicity * 1e3,
        color="0.3",
        linestyle="--",
        linewidth=1.2,
    )
    # Deep sinc nulls would otherwise stretch the log axis over ten decades.
    axis.set_ylim(peak * 1e-4, peak * 3)
    axis.text(
        device.anharmonicity * 1e3,
        peak * 2,
        r"  $\alpha/2\pi$ (1-2 transition)",
        color="0.3",
        fontsize=9,
        verticalalignment="top",
    )
    axis.set(
        title="drive spectrum; the marked weight at the anharmonicity is what leaks",
        xlabel="detuning from the qubit drive [MHz]",
        ylabel=r"$|\int\Omega e^{i\Phi}e^{i2\pi ft}dt|$ [rad]",
    )
    axis.grid(alpha=0.25, which="both")
    axis.legend(fontsize=8, loc="upper left", framealpha=0.9)
    figure.tight_layout()
    return figure


#: Colours for waveforms the demo does not name.  Compared as normalized RGBA
#: against ``db_helpers.PULSE_COLORS``, because "tab:blue" and "#1f77b4" are the
#: same colour written two ways and a string comparison would let it repeat.
SPARE_COLORS = (
    "tab:red", "tab:purple", "tab:brown",
    "tab:pink", "tab:olive", "tab:cyan",
)


def color_cycle(pulses):
    """Reuse the demo colours where they exist, extend them where they do not."""
    from matplotlib.colors import to_rgba

    used = {to_rgba(color) for color in db_helpers.PULSE_COLORS.values()}
    spare = (color for color in SPARE_COLORS if to_rgba(color) not in used)
    colors = {}
    for name in pulses:
        color = db_helpers.PULSE_COLORS.get(name)
        if color is None:
            color = next(spare)
            used.add(to_rgba(color))
        colors[name] = color
    return colors
